### ISSUE TITLE
Akonadi fails to start

### ISSUE THREAD

**Issue by pofl** [flathub/org.kde.kontact#34] opened 2019-08-27 13:20 UTC
This is the output of `flatpak run org.kde.kontact` after freshly installing it from flathub:

```
Akonadi is not running.
kbuildsycoca5 running...
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
org.kde.pim.akonadiserver: Starting up the Akonadi Server...
Cannot mix incompatible Qt library (version 0x50c03) with this library (version 0x50c04)
org.kde.pim.akonadicontrol: ProcessControl: Application "/app/bin/akonadiserver" stopped unexpectedly ( "Process crashed" )
org.kde.pim.akonadicontrol: Application '/app/bin/akonadiserver' crashed! 1 restarts left.
org.kde.pim.akonadiserver: Starting up the Akonadi Server...
Cannot mix incompatible Qt library (version 0x50c03) with this library (version 0x50c04)
org.kde.pim.akonadicontrol: ProcessControl: Application "/app/bin/akonadiserver" stopped unexpectedly ( "Process crashed" )
org.kde.pim.akonadicontrol: Application '/app/bin/akonadiserver' crashed! 0 restarts left.
org.kde.pim.akonadiserver: Starting up the Akonadi Server...
Cannot mix incompatible Qt library (version 0x50c03) with this library (version 0x50c04)
org.kde.pim.akonadicontrol: ProcessControl: Application "/app/bin/akonadiserver" stopped unexpectedly ( "Process crashed" )
org.kde.pim.akonadicontrol: Application '/app/bin/akonadiserver' crashed too often. Giving up!
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
org.kde.pim.akonadiserver: Starting up the Akonadi Server...
Cannot mix incompatible Qt library (version 0x50c03) with this library (version 0x50c04)
org.kde.pim.akonadicontrol: ProcessControl: Application "/app/bin/akonadiserver" stopped unexpectedly ( "Process crashed" )
org.kde.pim.akonadicontrol: Application '/app/bin/akonadiserver' crashed! 1 restarts left.
org.kde.pim.akonadiserver: Starting up the Akonadi Server...
Cannot mix incompatible Qt library (version 0x50c03) with this library (version 0x50c04)
org.kde.pim.akonadicontrol: ProcessControl: Application "/app/bin/akonadiserver" stopped unexpectedly ( "Process crashed" )
org.kde.pim.akonadicontrol: Application '/app/bin/akonadiserver' crashed! 0 restarts left.
org.kde.pim.akonadiserver: Starting up the Akonadi Server...
Cannot mix incompatible Qt library (version 0x50c03) with this library (version 0x50c04)
org.kde.pim.akonadicontrol: ProcessControl: Application "/app/bin/akonadiserver" stopped unexpectedly ( "Process crashed" )
org.kde.pim.akonadicontrol: Application '/app/bin/akonadiserver' crashed too often. Giving up!
org.kde.pim.kidentitymanagement: IdentityManager: There was no default identity. Marking first one as default.
No text-to-speech plug-ins were found.
org.kde.knotifications: env says KDE is running but SNI unavailable -- check KDE_FULL_SESSION and XDG_CURRENT_DESKTOP
org.kde.pim.akonadicore: Job error:  "" for collection: QVector() 

org.kde.pim.akonadicore: Job error:  "" for collection: QVector() 

org.kde.pim.messagelist: Failed to load tags  ""
org.kde.pim.kmail: ""
org.kde.pim.kmail: ""
WebEnginePage::javaScriptConsoleMessage lineNumber:  19  message:  "Uncaught TypeError: Cannot read property 'compareDocumentPosition' of null"
"https://dot.kde.org/rss.xml"
"https://www.linux.com/feeds/rss"
"https://planetkde.org/rss20.xml"
"https://store.kde.org/content.rdf"
"https://planetkde.org/pt-br/rss20.xml"
"https://planet.kde-espana.org/atom.xml"
kio_http_cache_cleaner: Already running!
kio_http_cache_cleaner: Already running!
kio_http_cache_cleaner: Already running!
kio_http_cache_cleaner: Already running!
^C
D-Bus session bus is not available!                                                                 
/app/bin/run_kontact.sh: line 3:   140 Aborted                 kontact "$@"
```

**Comment by danvratil** [comment] 2019-09-01 10:20
Looks like the latest KDE Frameworks runtime update has updated Qt, which crashes Akonadi. I'll correct that in the upcoming 19.08 update.

**Comment by lyro** [comment] 2020-02-28 11:54
I've stumbled about the same problem. Is there anything I can do *right now* (like using an older runtime)?

**Comment by pnunn** [comment] 2022-07-10 11:38
I've just hit something similar, but not quite the same.
org.kde.pim.akonadiserver: Starting up the Akonadi Server...                                                                                                                                                        
Cannot mix incompatible Qt library (5.15.3) with this library (5.15.5)

I'm on KDE Neon and trying to use the flatpak testing install of kontact.

**Comment by BeatLink** [comment] 2022-11-24 01:42
For those of you stumbling on this issue, I finally got my build working again with a temporary solution until this is fixed. Basically you have to downgrade and freeze the KDE runtime used by Kontact to get it to work. Here's the command i used.

```bash
sudo flatpak update --commit=2912e39b2c30c207025b9ad34882bf642904502da21811c3e9e4bf2e5bccbcd7 org.kde.Platform/x86_64/5.15-21.08
sudo flatpak mask org.kde.Platform/x86_64/5.15-21.08
```

**Comment by CarlSchwan** [comment] 2022-11-24 10:18
Basiclly the issue is that QtWebEngine is not part of the Qt/KDE runtime and QtWebEngine use private apis. We should somehow find a way to rebuild the flatpak when the runtime update :(

**Comment by travier** [comment] 2022-11-24 14:20
I'll trigger a build for this app now. Won't fix things long term of course.

**Comment by Zahrun** [comment] 2023-02-28 17:57
> For those of you stumbling on this issue, I finally got my build working again with a temporary solution until this is fixed. Basically you have to downgrade and freeze the KDE runtime used by Kontact to get it to work. Here's the command i used.
> 
> ```shell
> sudo flatpak update --commit=2912e39b2c30c207025b9ad34882bf642904502da21811c3e9e4bf2e5bccbcd7 org.kde.Platform/x86_64/5.15-21.08
> sudo flatpak mask org.kde.Platform/x86_64/5.15-21.08
> ```

I tried this but get this:
`kontact: symbol lookup error: /app/lib/libKF5PimCommonAutoCorrection.so.5: undefined symbol: _ZN11KMessageBox17warningTwoActionsEP7QWidgetRK7QStringS4_RK8KGuiItemS7_S4_6QFlagsINS_6OptionEE`

Is the new build supposed to be working?

**Closed** 2023-03-08 15:20 UTC
